// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTkHisVD2ZA-CDWLRiL3K-fJm2V3-H0Q4',
    appId: '1:490616636551:web:b494a38d8a8db4e52d2422',
    messagingSenderId: '490616636551',
    projectId: 'meu-app-medicamentos',
    authDomain: 'meu-app-medicamentos.firebaseapp.com',
    storageBucket: 'meu-app-medicamentos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKd_TTfVEWhfin0M4_tUCtt7kCzi48OQ',
    appId: '1:490616636551:android:a374fdd1596ee7d12d2422',
    messagingSenderId: '490616636551',
    projectId: 'meu-app-medicamentos',
    storageBucket: 'meu-app-medicamentos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYOG889t1BpOZ9nXqlTuyFDhCibCXGk9Q',
    appId: '1:490616636551:ios:5ea82ecbbee761f22d2422',
    messagingSenderId: '490616636551',
    projectId: 'meu-app-medicamentos',
    storageBucket: 'meu-app-medicamentos.firebasestorage.app',
    iosBundleId: 'com.example.nomeDoProjeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYOG889t1BpOZ9nXqlTuyFDhCibCXGk9Q',
    appId: '1:490616636551:ios:5ea82ecbbee761f22d2422',
    messagingSenderId: '490616636551',
    projectId: 'meu-app-medicamentos',
    storageBucket: 'meu-app-medicamentos.firebasestorage.app',
    iosBundleId: 'com.example.nomeDoProjeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTkHisVD2ZA-CDWLRiL3K-fJm2V3-H0Q4',
    appId: '1:490616636551:web:c577abc30481e12f2d2422',
    messagingSenderId: '490616636551',
    projectId: 'meu-app-medicamentos',
    authDomain: 'meu-app-medicamentos.firebaseapp.com',
    storageBucket: 'meu-app-medicamentos.firebasestorage.app',
  );

}